### ISSUE TITLE
large firmware

### ISSUE THREAD

**Issue by brianreinhold** [JZimnol/pico_fota_bootloader#2]
This is not a bug but there is no discussion board that I can see,

How much non-firmware memory does the bootloader take?  I have a uf2 file of size 2,178,560 bytes on my computer. Is this too large for this bootloader to handle?

**Comment by JZimnol** [comment]
Can you please specify what do you mean by `non-firmware memory`?

Also, please keep in mind that the size of the `uf2` file is not equal to the size of the generated binary (because of additional data it contains). You should check the size of the `.bin` file in order to make sure it fits the downlaod partition.

**Comment by brianreinhold** [comment]
Sorry about the vagueness - by non-firmware memory, all the memory taken up by the bootloader (so I have some idea how much space is left and if my firmware can fit)

**Comment by JZimnol** [comment]
As specified in [README](https://github.com/JZimnol/pico_fota_bootloader/blob/master/README.md), current configuration reserves 36k for the bootloader + 4k for the non-volatile configuration. The bootloader itself is smaller, but I've reserved 36k for future expansion (e.g. new functionalities). That's why Application and Download partitions take 1004k.

**Comment by brianreinhold** [comment]
Bummer - my firmware bin file is 1064 kb, plus I need space for device information files and FHIR upload files. We are tight on space!

**Comment by JZimnol** [comment]
There is nothing I can do probably. You can use some external memory to write the download file into e.g. SD card and modify bootloader's write/read functions properly.
